pool:
  name: Hosted Ubuntu 1604

trigger:
  branches:
    include:
        - master
  paths:
    include: 
        - 'apis/user-java'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'OHDevOps'
    repository: 'api-user-java'
    command: 'buildAndPush'
    Dockerfile: '**/apis/user-java/Dockerfile'
    tags: '$(Build.BuildId)'
